# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

sudo: false

env:
  global:
    - TA_INCLUDE_PATH=$HOME/dependencies/include
    - TA_LIBRARY_PATH=$HOME/dependencies/lib
    - LD_LIBRARY_PATH=$HOME/dependencies/lib

before_install:
  - mkdir $HOME/dependencies
  - wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
  - tar -xvzf ta-lib-0.4.0-src.tar.gz
  - cd ta-lib/ && ./configure --prefix=$HOME/dependencies && make install && cd .. && rm -r ta-lib

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -q -e .
    - pip install -U pytest pytest-cov coverage codecov tox flake8

# command to run tests, e.g. python setup.py test
script:
    - py.test tests/

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: basaks
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: basaks/marketcrush
    condition: $TOXENV == py27
