data:
    - path: sample_data/demo_data1.csv
    - path: sample_data/demo_data2.csv

strategy: trend_daily

parameters:
    short_tp: 10  # MA fast period
    long_tp: 20 # MA slow period
    filter_fp: 30  # filter fast period
    filter_sp: 60  # filter slow period
    # The strategy does not risk more than 20 bps per trade
    risk_factor: 0.002  # 20 bps
    initial_cap: 1000000.0
    # exit position if price falls below this fraction X atr from
    # best position value
    atr_exit_fraction: 3.0
    atr_stops_period: 10  # atr lookback period
    max_hold_time: 300  # minutes, not used yet
    commission: 0.0002  # 2 bps
    # point value of future cotract, i.e., profit or loss for one unit of price
    # movement of the contract
    point_value: 100
    day_trade: True

output:
    file: output.xlsx  # has to be .xlsx

show_plot: True
